config/routes.rb
LBiOrigins::Application.routes.draw do
  resources :departments
  resources :people

  resources :map do
    collection do
      get 'people'
    end
  end

  

  root :to => "map#index"

end

app/models/department.rb
class Department < ActiveRecord::Base
  
  has_many :people
  
  validates_presence_of :name
  
  scope :alphabetical, order("name")
    
end

app/models/google_maps.rb
class GoogleMaps
  include HTTParty
  
  #base_uri "maps.google.com"
  
  # Given an address will return a hash with :lat and :lng as keys, otherwise nil
  def self.geocode(address)
    result = get("http://maps.google.com/maps/api/geocode/json?sensor=false", :query => {:address => address })
    if result.parsed_response["results"].length > 0
      return { :lat => result.parsed_response["results"][0]["geometry"]["location"]["lat"].to_f,
               :lng => result.parsed_response["results"][0]["geometry"]["location"]["lng"].to_f } 
    end
    nil
  end
  
end

app/models/person.rb
class Person < ActiveRecord::Base
  
  belongs_to :department
  
  validates_presence_of :first_name, :last_name, :home_town, :home_country, :latitude, :longitude, :department_id
  
  before_validation :geocode_if_neccesary

  protected
  
  def geocode_if_neccesary
    geocode if self.latitude.nil? && self.longitude.nil?
  end
  
  def geocode
    address = "#{home_town}, #{home_country}"
    location = GoogleMaps.geocode(address)
    
    if location
      self.latitude, self.longitude = location[:lat], location[:lng]
      
      # If another user has the same location, randomise by a small amount
      # so their pin's dont cover each other
      if (Person.where(:latitude => self.latitude, :longitude => self.longitude).count > 0)
        self.latitude  += (rand(150)-100).to_f/10000
        self.longitude += (rand(150)-100).to_f/10000
      end

    end
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  ADMIN_USER = "admin"
  ADMIN_PASSWORD =  ENV["admin_password"]
  
  private
  
  def check_is_admin
    
    authenticate_or_request_with_http_basic do |id, password| 
      (id == ADMIN_USER && password == ADMIN_PASSWORD)
    end
    
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :check_is_admin
  
  # GET /departments
  # GET /departments.xml
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.xml
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.xml
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.xml
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to(@department, :notice => 'Department was successfully created.') }
        format.xml  { render :xml => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.xml
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to(@department, :notice => 'Department was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.xml
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to(departments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  
  # GET /map
  def index
    @person = Person.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def people
     @people = Person.all

      respond_to do |format|
        format.json  { render :json => @people.to_json(:include => :department) }
      end
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :check_is_admin, :except => [:create]
  
  respond_to :html, :js, :json
  
  # GET /people
  # GET /people.xml
  def index
    @people = Person.order("last_name, first_name")

    respond_with(@people)
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_with(@person)
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_with(@person)
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    flash[:notice] = "Comment successfully created" if @person.save
    respond_with(@person, :layout => !request.xhr?)
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.json  { head :ok }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>

		<title>LBi | Origins</title>

		<%= stylesheet_link_tag "global.css" %>
		<%= csrf_meta_tag %>
		
		<meta content="charset=utf-8">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<link rel="stylesheet" href="stylesheets/global.css" type="text/css">
		<link media="handheld, only screen and (max-device-width:480px)" href="stylesheets/antiScreen.css" rel="stylesheet">
	</head>
	<body>

		<%= yield %>

		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<%= javascript_include_tag :defaults %>
		
	</body>
</html>

app/views/map/_form.html.erb
<%= form_for(@person, :remote => true) do |f| %>
  <a id="close" href="#">Close</a>
  <div class="errors"></div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label "Home town (be specific)" %><br />
    <%= f.text_field :home_town %>
  </div>
  <div class="field">
    <%= f.label :home_country %><br />
    <%= f.text_field :home_country %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.collection_select(:department_id, Department.alphabetical, :id, :name, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :alumni %><br />
    <%= f.check_box (:alumni) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map/index.html.erb
<!-- header -->
<div id="header">
	<p class="description">Explore this map to discover where everyone in LBi are from.
	<br />You can add yourself using the link below.<br/><br/><a id="addOrigin" href="#"> Add your origin</a></p>
	<h1>LBi<br />Origins</h1>
</div>

<div id="legend">
    <p id="lbi">LBi Employees</p>
    <p id="alumni">LBi Alumni</p>
</div>

<div id="form">
    <div id="screen"></div>
    <%= render "form" %>
</div>

<!-- eo form -->
<div id="map_canvas">
</div>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :home_town %><br />
    <%= f.text_field :home_town %>
  </div>
  <div class="field">
    <%= f.label :home_country %><br />
    <%= f.text_field :home_country %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
	<%= f.collection_select(:department_id, Department.alphabetical, :id, :name, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :alumni %><br />
    <%= f.check_box (:alumni) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/create.js.erb
var el = $('#new_person');

<% if @person.errors.any? %>
  // Create a list of errors
  var errors = $('<ul>');

  <% @person.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>
  errors.append("</ul>")

  // Display errors on form
  el.find('.errors').html(errors);

<% else %>

	// Hide form
	$('#form').css({
		'display' : 'none'
	});

	// Clear form
	el.find('input:text').val('');
	el.find('.errors').empty();
  	
	var json = <%= raw @person.to_json(:include => :department) %>;

	placeMarker(json.person);
	
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Home town</th>
    <th>Home country</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Department Id</th>
    <th>Alumni</th>
    <th>Created At</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= person.home_town %></td>
    <td><%= person.home_country %></td>
    <td><%= person.longitude %></td>
    <td><%= person.latitude %></td>
    <td><%= person.department_id %></td>
    <td><%= person.alumni %></td>
    <td><%= person.created_at %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Home town:</b>
  <%= @person.home_town %>
</p>

<p>
  <b>Home country:</b>
  <%= @person.home_country %>
</p>

<p>
  <b>Longitude:</b>
  <%= @person.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @person.latitude %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>